### ISSUE TITLE
Map doesn't update 

### ISSUE THREAD

**Issue by protected22** [jpenilla/squaremap#81]
Is there a way to get the map to update itself? It still shows buildings and places which already got changed some days ago my players in the world.

**Comment by jpenilla** [comment]
By default, the map will update when things change, although change detection is most complete on Paper, some things might get missed on Fabric/Sponge. Are you still having this issue with squaremap 1.1.9? Locally everything seems to be working fine and I can't reproduce this.

**Comment by protected22** [comment]
Hi. I believe it got fixed in 1.1.9. I notice it changes, but only after my server restarts. Probably something in Paper which causes that. But since my server now restarts every night, it isn't that much of a issue anymore.

**Comment by mxrtxn36** [comment]
I use paper in 1.19.3 without any issues

**Comment by jpenilla** [comment]
Reporter says their issue is solved, and issue has not been reproduced. Closing

**Comment by Agaloth** [comment]
This bug still happens to me, nothing is updating after the server has been up for more than 3 hours, the player list doesn't get updated either.
